services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: flowforge
      POSTGRES_USER: flowforge
      POSTGRES_PASSWORD: flowforge
    ports:
      - "5432:5432"
    volumes:
      - flowforge-postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  flowforge-postgres:
